# Generated by Django 5.1.1 on 2025-08-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost_price',
            new_name='unit_price',
        ),
    ]
